Dev 1 week
Dev-incubator/WebAutoparkIvan pull request #2
Opened 2021-07-27 07:20 UTC by kuzmiich

2021-07-27 10:34 UTC, PushMeNow requested changes

2021-07-27 10:34 UTC, PushMeNow commented on WebAutopark.Core/Entities/Base/Entity.cs
> +        public int Id { get; set; }
Usually we don't use name for identifier just 'Id' because it is pretty vague name: id for what? You have to give name for Id uniquely.

2021-07-27 10:34 UTC, PushMeNow commented on WebAutopark.BusinessLogic/Services/IService.cs
> +    public interface IService
Why do you need this interface?

2021-07-27 10:34 UTC, PushMeNow commented on WebAutopark.Core/Entities/Vehicle.cs
> +        public double GetCalcTaxPerMonth => (Weight * WeightCoefficient) + (VehicleType.TaxCoefficient * TaxCoefficient) + ShiftForTax;
Redudant brackets.

2021-07-27 10:34 UTC, PushMeNow commented on WebAutopark.DataAccess/Repositories/DetailRepository.cs
> +        public async void Create(Detail element) => await Connection.ExecuteAsync(QueryCreate, element);
Never use 'void' keyword for async method it is obsolete and not stable approach.

2021-07-27 10:34 UTC, PushMeNow commented on WebAutopark.DataAccess/Repositories/Base/IRepository.cs
> +        void Save();
Save method is redundant when you are using Dapper.

2021-07-27 10:34 UTC, PushMeNow commented on WebAutopark.DataAccess/Repositories/Base/IRepository.cs
> +        void Update(T element);
Why your Get methods are async but method for data manipulation are not?

2021-07-27 10:34 UTC, PushMeNow commented on WebAutopark/Startup.cs
> +            services.AddTransient<IRepository<Detail>, DetailRepository>(_ => new DetailRepository(new DbConnectionBuilder(connectionString)));
Why are you describing entity provider for repositories? You can describe it for DbConnectionBuilder and it will be done automatically. Also Repositories and Services should have Scoped life time because these classes should be created one on request. There is no seance to create their on each call of DI.

2021-07-27 14:35 UTC, kuzmiich commented on WebAutopark/Startup.cs
> +            services.AddTransient<IRepository<Detail>, DetailRepository>(_ => new DetailRepository(new DbConnectionBuilder(connectionString)));
Moved it into a separate variable and changed the scope

2021-07-27 14:39 UTC, kuzmiich commented on WebAutopark/Startup.cs
> +            services.AddTransient<IRepository<Detail>, DetailRepository>(_ => new DetailRepository(new DbConnectionBuilder(connectionString)));
may be it`s not correct

2021-07-28 10:14 UTC, kuzmiich commented on WebAutopark/Startup.cs
> +            services.AddTransient<IRepository<Detail>, DetailRepository>(_ => new DetailRepository(new DbConnectionBuilder(connectionString)));
fixed it in last commit

2021-07-28 19:08 UTC, PushMeNow requested changes

2021-07-28 19:08 UTC, PushMeNow commented on WebAutopark.DataAccess/Repositories/Specification/ConnectionRepository.cs
> +            QueryGetAll =  $"SELECT * FROM {dbName}";
If you would like to describe common information about entity you can create class EntityInfo (it is just example for name) which will contain whole need information about entity (table, PK name etc.) and include it contructure. Also you can move it on higher level and use fro example pattern Provider. Create entity info provider which will provide you filled entity info by your entity type, include this provider and get it in constructor then just call method of provider which will return you entity info.

2021-07-31 20:38 UTC, aces47 approved these changes
Good job.

2021-08-02 08:46 UTC, PushMeNow requested changes

2021-08-02 08:46 UTC, PushMeNow commented on WebAutopark.Core/Entities/Base/Entity.cs
> +    public abstract class Entity
Why have you returned this class?

2021-08-02 08:46 UTC, PushMeNow commented on WebAutopark.DataAccess/Repositories/Specification/ConnectionRepository.cs
> +        protected ConnectionRepository(DbConnection dbConnection, Entity entity) : this(entity)
I don't understand why do you need Entity class here? Here must be Type.

2021-08-02 08:46 UTC, PushMeNow commented on WebAutopark/Startup.cs
> +            services.AddTransient<IDbProvider>(_ => new DbProvider());
Scoped and without describing  of provider. Just <IDbProvider,DbProvider>

2021-08-02 08:55 UTC, PushMeNow requested changes

2021-08-02 08:55 UTC, PushMeNow commented on WebAutopark.DataAccess/Repositories/Specification/ConnectionRepository.cs
> +        private static IDbProvider _dbProvider;
Where is initialization of this field?

2021-08-02 08:55 UTC, PushMeNow commented on WebAutopark.DataAccess/Repositories/Specification/Provider/DbProvider.cs
> +    }
![image](https://user-images.githubusercontent.com/33716293/127833464-16be738d-3779-4d34-bf46-c38d256726a0.png)

2021-08-02 18:50 UTC, PushMeNow approved these changes

2021-08-02 18:50 UTC, merged